export const ACTION_ADD_COURSE = "ACTION_ADD_COURSE"
export const ACTION_DELETE_COURSE = "ACTION_DELETE_COURSE"
export const ACTION_EDIT_COURSE = "ACTION_EDIT_COURSE";
export const ACTION_CHANGE_PAGE = "ACTION_CHANGE_PAGE"